server:
  port: 9090

spring:
  jackson:
    default-property-inclusion: non_null
    # 设置json的时候给时区+8个小时
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 118.178.141.57
    port: 6379
    password: 123abc
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.178.141.57:3306/finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123abc
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.sy.finance.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml

pagehelper:
  helperDialect: mysql
  page-size-zero: true
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
